plugins:
  autograder_enabled:
    default: true
    client: true

  autograder_liver_category_id:
    default: 7
    type: integer
    client: false

  autograder_lung_category_id:
    default: 8
    type: integer
    client: false

  autograder_dual_participation_bonus:
    default: 5
    type: integer
    client: false

  autograder_grader_url:
    default: ""
    type: string
    client: false

  autograder_grader_auth_token:
    default: ""
    type: string
    client: false
    secret: true
